site_name: Final Hour Documentation
site_author: eagle_eyed<blind.lightning.productions@gmail.com>
site_description: the documentation for the final hour audio game, an audio FPS inspired by Call of Duty Zombies. 
site_url: https://finalhour.lowerelements.club/docs
nav:
  - Home: index.md
  - Gameplay:
    - User interface:
      - Menus: gameplay/ui/menu.md
      - Text dialogs: gameplay/ui/text_dialog.md
    - Chapter 1 - configuring the game and getting connected: gameplay/chapter1.md
    - Chapter 2 - Navigating the map: gameplay/chapter2.md
    - Chapter 3 - Weapons: gameplay/chapter3.md
    - User interface:
      - Menus: gameplay/ui/menu.md
  - Map building: xml_map_syntax.md
  - Credits: credits.md
  - The Log querying language (usable by moderators only): log_queries.md
